install/install_for_macos_linux.sh, install/install_for_windows.ps1
=> :book: correct url since we are tipi.build !

.github/workflows/check_install_script.yaml, CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
=> :rocket: preparing v0.0.16.

.github/workflows/check_install_script.yaml, CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
- Smart auto include path computation detection to complement convention detection
- Eclipse project support with remote tipi build
- Local & remote Monorepo dependencies support
- Remote git subfolder dependencies support 
- Running commands in tipi environment with `tipi run command` on unixes support multiple arguments ( not only a string)
- Windows TLS environments supports downloading Platform libs from server with recent ciphersuites
=> Release v0.0.18

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
Fixes build dir synchronization bug that always happens by default but shouldnt.
=> Release v0.0.25

.github/workflows/check_install_old_version.yaml, .github/workflows/check_install_script.yaml, install/install_for_macos_linux.sh, install/install_for_windows.ps1
- cleaned up messages
- fixed #34
- "fixed" #31 by testing writability and outputting appropriate message to the user
- Added detection for the tipi install folder already being on PATH
- Improved and unified a bunch of messages
- 
fix nxxm/nxxm-src#674
=> Improvements windows installer script

.github/workflows/check_install_old_version.yaml, .github/workflows/check_install_script.yaml, CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
=> Feature/release v0.0.32

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
This new releases provides alot of fixes and speed up and improvements ! A really enjoyable tipi version ! ❗ ❤️ 😄
=> Release v0.0.38 - Blissful Buffalo

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
The changelog and scripts default version changes for the new version.
=> :gear: v0.0.39 fixing cache creation for files built before committing.

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
Attached CHANGELOG and scripts adaptation.
=> :fire: :fox_face: release v0.0.43 Flamboyant Fox

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
Changelog and script version bump for upcoming version.
=> :fish: Glorious Goldfish v0.0.44

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
The purpose of this pr is to prepare and release version v0.0.47
=> 🚀 Release v0.0.47

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
=> :rocket: release v0.0.46

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
The purpose of this pr is to release version v0.0.52 of tipi
=> 🚀 Release v0.0.52

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
the purpose of this pr is to prepare the release v0.0.53
=> Release v0.0.53

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
The purpose of this pr is to prepare the next release of tipi
=> 🚀 prepare release v0.0.54

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
the aim of this pr is to adapt  install script to new release package format
=> New release package format

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
=> Prepare release v0.0.57

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
Hotfix release that should finally make it as stable release :-)
Superseeding #85
=> Feature/prepare v0.0.60

CHANGELOG.md, install/container/centos.sh, install/container/ubuntu.sh, install/install_for_macos_linux.sh, install/install_for_windows.ps1
the purpose of this pr is to prepare the release v0.0.62
=> Release v0.0.62

CHANGELOG.md, install/install_for_macos_linux.sh, install/install_for_windows.ps1
the purpose of this pr is to prepare the release v0.0.61 of tipi
=> Release v0.0.61
